import { cspellConfig } from '@kitschpatrol/cspell-config'

export default cspellConfig({
	words: [
		'Alos',
		'bgdark',
		'blep',
		'dailymotion',
		'Ewma',
		'gesturesdisabled',
		'lightboxes',
		'loadcomplete',
		'mediaaudiotrackunavailable',
		'mediacontroller',
		'mediaenterfullscreenrequest',
		'mediaisfullscreen',
		'mediapaused',
		'mediavolumeunavailable',
		'mixcloud',
		'msrc',
		'oembed',
		'oscnord',
		'pswp',
		'reposts',
		'srcsets',
		'unassociate',
		'userinactive',
		'userinactivechange',
		'youtu',
		'Zoomable',
	],
})
