packages:
  - .
  - playground
  - playground-starlight

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
