packages:
  - .
  - playground
  - playground-starlight
  - test/parity/fixtures/core-image
  - test/parity/fixtures/picture-darkmode
ignoreWorkspaceRootCheck: true
publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
allowBuilds:
  esbuild: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
  ws: true
minimumReleaseAgeExclude:
  - '@astrojs/*'
  - '@cspell/*'
  - '@kitschpatrol/*'
  - astro
  - astro-mdx-kit
  - cspell
  - cspell-config-lib
  - cspell-dictionary
  - cspell-gitignore
  - cspell-glob
  - cspell-grammar
  - cspell-io
  - cspell-lib
  - cspell-trie-lib
